[package]
name = "icons"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { path = "../config" }
yew = { git = "https://github.com/yewstack/yew.git", features = ["csr"] }

[build-dependencies]
walkdir = "2"
